server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://192.168.178.70:3100/loki/api/v1/push

scrape_configs:
- job_name: windows
  windows_events:
    use_incoming_timestamp: false
    bookmark_path: C:\promtail\bookmark.xml
    eventlog_name: "Application"
    xpath_query: '*'
    labels:
      job: windows
  relabel_configs:
    - source_labels: ['computer']
      target_label: 'host'
