server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://logging:3100/loki/api/v1/push

scrape_configs:
- job_name: Application
  pipeline_stages:
  
  - json:
      expressions:
        event_id: event_id
        eventRecordID: eventRecordID
  - labels:
      event_id:
      eventRecordID:
      

  windows_events:
    use_incoming_timestamp: false
    bookmark_path: C:\promtail\bookmark.xml
    eventlog_name: "Application"
    xpath_query: '*'


  relabel_configs:
    - source_labels: ['computer']
      target_label: 'host'

- job_name: System
  pipeline_stages:
  
  - json:
      expressions:
        event_id: event_id
        eventRecordID: eventRecordID 
  - labels:
      event_id:
      eventRecordID:

  windows_events:
    use_incoming_timestamp: false
    bookmark_path: C:\promtail\main\promtail-main\bookmark.xml
    eventlog_name: "System"
    xpath_query: '*'

- job_name: Security
  pipeline_stages:
  
  - json:
      expressions:
        event_id: event_id
        eventRecordID: eventRecordID
  - labels:
      event_id:
      eventRecordID:


  windows_events:
    use_incoming_timestamp: false
    bookmark_path: C:\promtail\main\promtail-main\bookmark.xml
    eventlog_name: "Security"
    xpath_query: '*'

- job_name: Setup
  pipeline_stages:
  
  - json:
      expressions:
        event_id: event_id
        eventRecordID: eventRecordID
  - labels:
      event_id:
      eventRecordID:


  windows_events:
    use_incoming_timestamp: false
    bookmark_path: C:\promtail\main\promtail-main\bookmark.xml
    eventlog_name: "Setup"
    xpath_query: '*'
